// <auto-generated />
using System;
using Ejemplo0.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejemplo0.Migrations
{
    [DbContext(typeof(SchoollContext))]
    partial class SchoollContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ejemplo0.Modelo.Grado", b =>
                {
                    b.Property<int>("IdGrados")
                        .HasColumnType("int");

                    b.Property<string>("NombreGrado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdGrados");

                    b.ToTable("Grados");

                    b.HasData(
                        new
                        {
                            IdGrados = 1,
                            NombreGrado = "Primer",
                            Seccion = "A"
                        },
                        new
                        {
                            IdGrados = 2,
                            NombreGrado = "Segundo",
                            Seccion = "B"
                        });
                });

            modelBuilder.Entity("Ejemplo0.Modelo.Studiante", b =>
                {
                    b.Property<int>("IdStudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudiante"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdGrado")
                        .HasColumnType("int");

                    b.Property<string>("NombreStudiante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStudiante");

                    b.HasIndex("IdGrado");

                    b.ToTable("Studiantes");

                    b.HasData(
                        new
                        {
                            IdStudiante = 1,
                            DateOfBirth = new DateTime(2018, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdGrado = 1,
                            NombreStudiante = "Manolo Sanchez"
                        },
                        new
                        {
                            IdStudiante = 2,
                            DateOfBirth = new DateTime(2016, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdGrado = 2,
                            NombreStudiante = "Manue Pedrolo"
                        },
                        new
                        {
                            IdStudiante = 3,
                            DateOfBirth = new DateTime(2017, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdGrado = 1,
                            NombreStudiante = "Kequito Dulce"
                        });
                });

            modelBuilder.Entity("Ejemplo0.Modelo.Studiante", b =>
                {
                    b.HasOne("Ejemplo0.Modelo.Grado", "Grado")
                        .WithMany()
                        .HasForeignKey("IdGrado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grado");
                });
#pragma warning restore 612, 618
        }
    }
}
